## Overview Of Linear Algebra

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = np.linspace(0,50,1000)

y1 = 30*x + 1000
y2 = 50*x + 100

plt.plot(x, y1, c='orange')
plt.plot(x, y2, c='blue')
plt.show()

## Representing Functions In General Form

![Jupyter](./equation_to_matrix.svg)

## Representing An Augmented Matrix In NumPy

In [3]:
matrix_one = np.asarray([
    [30, -1, -1000],
    [50, -1, -100]  
], dtype=np.float32)

In [4]:
matrix_one

array([[   30.,    -1., -1000.],
       [   50.,    -1.,  -100.]], dtype=float32)

## Matrix Representation Of The Solution

![Jupyter](./matrix_to_equation.svg)

## Row Operations

In [5]:
matrix_one = np.asarray([
    [30, -1, -500],
    [50, -1, -100]  
], dtype=np.float32)

matrix_one[0] = matrix_one[0]/30

In [6]:
matrix_one

array([[ 1.0000000e+00, -3.3333335e-02, -1.6666666e+01],
       [ 5.0000000e+01, -1.0000000e+00, -1.0000000e+02]], dtype=float32)

## Simplifying Matrix To Echelon Form

![Jupyter](./echelon_one.svg)
![Jupyter](./echelon_two.svg)
![Jupyter](./echelon_three.svg)

In [7]:
matrix_three = np.asarray([
    [1, -1/30, -1000/30],
    [0, 1, 2350]  
], dtype=np.float32)

matrix_three[0] = matrix_three[0] + matrix_three[1]/30

In [8]:
matrix_three

array([[1.0000000e+00, 0.0000000e+00, 4.5000004e+01],
       [0.0000000e+00, 1.0000000e+00, 2.3500000e+03]], dtype=float32)

## Summerization

![Jupyter](./higher_order_system.svg)