## Basic Matrix Operations

![Jupyter](./valid_matrix_sums.svg)

![Jupyter](./matrix_addition.svg)

![Jupyter](./matrix_scalar_multiplication.svg)

## Matrix Vector Multiplication

![Jupyter](./matrix_vector_multiplication.svg)

![Jupyter](./valid_matrix_products.svg)

In [3]:
import numpy as np


In [5]:
matrix_a = np.asarray([[0.7, 3, 9],
                      [1.7, 2, 9],
                      [0.7, 9, 2]], dtype=float)

In [6]:
matrix_a

array([[0.7, 3. , 9. ],
       [1.7, 2. , 9. ],
       [0.7, 9. , 2. ]])

In [7]:
vector_b = np.asarray([[1],
                      [2],
                      [1]], dtype=int)

In [8]:
vector_b

array([[1],
       [2],
       [1]])

In [9]:
ab_product = np.dot(matrix_a, vector_b)

In [11]:
print(ab_product)

[[15.7]
 [14.7]
 [20.7]]


## Matrix Multiplication

In [12]:
matrix_a = np.asarray([
    [0.7, 3],
    [1.7, 2],
    [0.7, 9]
], dtype=np.float32)

matrix_b = np.asarray([
    [113, 3, 10],
    [1, 0, 1],
], dtype=np.float32)

In [14]:
product_ab = np.dot(matrix_a, matrix_b)

In [15]:
product_ba = np.dot(matrix_b, matrix_a)

## Matrix Transpose

In [16]:
matrix_a = np.asarray([
    [0.7, 3],
    [1.7, 2],
    [0.7, 9]
], dtype=np.float32)

matrix_b = np.asarray([
    [113, 3, 10],
    [1, 0, 1],
], dtype=np.float32)



In [18]:
transpose_a = matrix_a.T
print(transpose_a)

[[0.7 1.7 0.7]
 [3.  2.  9. ]]


In [19]:
print(transpose_a.T)

[[0.7 3. ]
 [1.7 2. ]
 [0.7 9. ]]


In [27]:
trans_ba = np.dot(matrix_b.T, matrix_a.T)

In [28]:
trans_ab = np.dot(matrix_a.T, matrix_b.T)

In [29]:
product_ab = np.dot(matrix_a, matrix_b)

In [30]:
print(product_ab.T)

[[ 82.1       194.1        88.1      ]
 [  2.1         5.1000004   2.1      ]
 [ 10.         19.         16.       ]]


In [31]:
print(trans_ab)

[[ 91.2   1.4]
 [435.   12. ]]


In [32]:
print(trans_ba)

[[ 82.1       194.1        88.1      ]
 [  2.1         5.1000004   2.1      ]
 [ 10.         19.         16.       ]]


## Identity Matrix

In [34]:
i_2 = np.identity(2)

i_3 = np.identity(3)


In [37]:

matrix_33 = np.random.normal(size=(3,3))

In [39]:
matrix_23 = np.random.normal(size=(2,3))

In [41]:

identity_33 = np.dot(i_3, matrix_33)

identity_23 = np.dot(i_2, matrix_23)

print(matrix_23)

print(identity_23)

print(matrix_33)
print(identity_33)

[[-0.86477321  1.16072436  0.83578073]
 [ 2.31806622 -1.11563813 -0.6328566 ]]
[[-0.86477321  1.16072436  0.83578073]
 [ 2.31806622 -1.11563813 -0.6328566 ]]
[[ 0.48270271  0.36829063  0.98991059]
 [ 1.13715745  1.04103407  0.43199768]
 [-1.53061757  0.561433   -0.77098601]]
[[ 0.48270271  0.36829063  0.98991059]
 [ 1.13715745  1.04103407  0.43199768]
 [-1.53061757  0.561433   -0.77098601]]


## Matrix Inverse

In [64]:
matrix_a = np.asarray([
    [1.5, 3],
    [1, 4]
])

def matrix_inverse_two(mat):
    det = (mat[0,0]*mat[1,1] - mat[0,1]*mat[1,0])
    if det == 0:
        raise ValueError("The matrix isn't invertible")
    right_mat = np.asarray([
        [mat[1,1], -mat[0,1]],
        [-mat[1,0], mat[0,0]]
    ])
    inv_mat = np.dot(1/det, right_mat)
    return inv_mat
inverse_a = matrix_inverse_two(matrix_a)
i_2 = np.dot(inverse_a, matrix_a)
print(i_2)

[[1. 0.]
 [0. 1.]]


## Solving The Matrix Equation

$\begin{bmatrix} x_1\\ x_2 \end{bmatrix} =  \left[\begin{array}{rr|r}
30 & -1 \\ 
50 & -1 
\end{array}\right]^{-1} \begin{bmatrix} -1000\\ -100 \end{bmatrix}$

In [66]:
matrix_a = np.asarray([
    [30, -1],
    [50, -1]
])

vector_b = np.asarray([
    [-1000],
    [-100]
])
matrix_a_inverse = np.linalg.inv(matrix_a)
solution_x = np.dot(matrix_a_inverse, vector_b)
print(solution_x)

[[  45.]
 [2350.]]


## Determinant For Higher Dimensions

In [67]:
matrix_22 = np.asarray([
    [8, 4],
    [4, 2]
])

matrix_33 = np.asarray([
    [1, 1, 1],
    [1, 1, 6],
    [7, 8, 9]
])

In [68]:
det_22 = np.linalg.det(matrix_22)

det_33 = np.linalg.det(matrix_33)